<!-- greater than '>' &gt; -->
<!-- less than '<' &lt; -->
<div class="line1">1  |// Example Array program</div>
<div class="line2">2  |// Filename: Array1.cpp#include&lt;stdio.h&gt;</div>
<div class="line3">3  |#include &lt;iostream&gt;</div>
<div class="line4">4  |</div>
<div class="line5">5  |using namespace std;</div>
<div class="line6">6  |</div>
<div class="line7">7  |class Student{</div>
<div class="line8">8  |	private:</div>
<div class="line9">9  |			string name;</div>
<div class="line10">10 |		int units_enrolled; </div>
<div class="line11">11 |				double rate_per_unit; </div>
<div class="line12">12 |	</div>
<div class="line13">13 |	public:</div>
<div class="line14">14 |		
<div class="line15">15 |		Student(); </div>
<div class="line16">16 |		Student(string);</div>	
<div class="line17">17 |			Student(string,int);</div>
<div class="line18">18 |			Student(string,int,double);</div>
<div class="line19">19 |			string get_name();</div>
<div class="line20">20 |			</div>double compute_tfee();</div>
<div class="line21">21 |	};</div>
<div class="line22">22 |</div>
<div class="line23">23 |</div>
<div class="line24">24 |</div>
<div class="line25">25 |</div>
<div class="line26">26 |</div>
<div class="line27">27 |</div>
<div class="line28">28 |</div>
<div class="line29">29 |</div>
<div class="line30">30 |</div>
<div class="line31">31 |</div>
<div class="line32">32 |</div>
<div class="line33">33 |</div>
<div class="line34">34 |</div>
<div class="line35">35 |</div>
<div class="line36">36 |</div>
<div class="line37">37 |</div>
<div class="line38">38 |</div>
<div class="line39">39 |</div>
<div class="line40">40 |</div>
<div class="line41">41 |</div>
<div class="line42">42 |</div>
<div class="line43">43 |</div>
<div class="line44">44 |</div>
<div class="line45">45 |</div>
<div class="line46">46 |</div>
<div class="line47">47 |</div>
<div class="line48">48 |</div>
<div class="line49">49 |</div>
<div class="line50">50 |</div>
<div class="line51">51 |</div>
<div class="line52">52 |</div>
<div class="line53">53 |</div>
<div class="line54">54 |</div>
<div class="line55">55 |</div>
<div class="line56">56 |</div>
<div class="line57">57 |</div>
<div class="line58">58 |</div>
<div class="line59">59 |</div>
<div class="line60">60 |</div>
